function getNativeDisplayBoundsPowerShellScript() {
  return [
    '[Console]::InputEncoding = New-Object System.Text.UTF8Encoding -ArgumentList $false',
    '[Console]::OutputEncoding = New-Object System.Text.UTF8Encoding -ArgumentList $false',
    '$OutputEncoding = [Console]::OutputEncoding',
    'Add-Type -AssemblyName System.Windows.Forms',
    '$items = foreach ($screen in [System.Windows.Forms.Screen]::AllScreens) {',
    '  [PSCustomObject]@{',
    '    deviceName = [string]$screen.DeviceName',
    '    isPrimary = [bool]$screen.Primary',
    '    x = [int]$screen.Bounds.X',
    '    y = [int]$screen.Bounds.Y',
    '    width = [int]$screen.Bounds.Width',
    '    height = [int]$screen.Bounds.Height',
    '  }',
    '}',
    '$items | ConvertTo-Json -Depth 4 -Compress',
  ].join('\n');
}

function getVisibleWindowTitlesPowerShellScript() {
  return [
    '[Console]::InputEncoding = New-Object System.Text.UTF8Encoding -ArgumentList $false',
    '[Console]::OutputEncoding = New-Object System.Text.UTF8Encoding -ArgumentList $false',
    '$OutputEncoding = [Console]::OutputEncoding',
    'Add-Type @"',
    'using System;',
    'using System.Collections.Generic;',
    'using System.Runtime.InteropServices;',
    'using System.Text;',
    'public static class DesktopPetVisibleWindows {',
    '  public delegate bool EnumWindowsProc(IntPtr hWnd, IntPtr lParam);',
    '  [StructLayout(LayoutKind.Sequential)] public struct RECT { public int Left; public int Top; public int Right; public int Bottom; }',
    '  [DllImport("user32.dll")] public static extern bool EnumWindows(EnumWindowsProc lpEnumFunc, IntPtr lParam);',
    '  [DllImport("user32.dll")] public static extern bool IsWindowVisible(IntPtr hWnd);',
    '  [DllImport("user32.dll")] public static extern IntPtr GetShellWindow();',
    '  [DllImport("user32.dll")] public static extern IntPtr GetAncestor(IntPtr hWnd, uint gaFlags);',
    '  [DllImport("user32.dll")] public static extern IntPtr GetLastActivePopup(IntPtr hWnd);',
    '  [DllImport("user32.dll", SetLastError=true)] public static extern int GetWindowText(IntPtr hWnd, StringBuilder text, int count);',
    '  [DllImport("user32.dll", SetLastError=true)] public static extern int GetWindowTextLength(IntPtr hWnd);',
    '  [DllImport("user32.dll")] public static extern bool GetWindowRect(IntPtr hWnd, out RECT rect);',
    '  [DllImport("user32.dll")] public static extern int GetWindowLong(IntPtr hWnd, int nIndex);',
    '  [DllImport("dwmapi.dll")] public static extern int DwmGetWindowAttribute(IntPtr hwnd, int dwAttribute, out int pvAttribute, int cbAttribute);',
    '}',
    '"@',
    'try { [System.Diagnostics.Process]::GetCurrentProcess().PriorityClass = [System.Diagnostics.ProcessPriorityClass]::Idle } catch {}',
    '$WS_EX_TOOLWINDOW = 0x00000080',
    '$WS_EX_APPWINDOW = 0x00040000',
    '$WS_EX_NOACTIVATE = 0x08000000',
    '$GWL_EXSTYLE = -20',
    '$GA_ROOTOWNER = 3',
    '$DWMWA_CLOAKED = 14',
    '$items = New-Object System.Collections.Generic.List[string]',
    '$shellWindow = [DesktopPetVisibleWindows]::GetShellWindow()',
    '[DesktopPetVisibleWindows]::EnumWindows({',
    '  param($hWnd, $lParam)',
    '  if ($hWnd -eq $shellWindow) { return $true }',
    '  if (-not [DesktopPetVisibleWindows]::IsWindowVisible($hWnd)) { return $true }',
    '  $length = [DesktopPetVisibleWindows]::GetWindowTextLength($hWnd)',
    '  if ($length -le 0) { return $true }',
    '  $exStyle = [DesktopPetVisibleWindows]::GetWindowLong($hWnd, $GWL_EXSTYLE)',
    '  if (($exStyle -band $WS_EX_TOOLWINDOW) -ne 0) { return $true }',
    '  if (($exStyle -band $WS_EX_NOACTIVATE) -ne 0 -and ($exStyle -band $WS_EX_APPWINDOW) -eq 0) { return $true }',
    '  $cloaked = 0',
    '  [void][DesktopPetVisibleWindows]::DwmGetWindowAttribute($hWnd, $DWMWA_CLOAKED, [ref]$cloaked, 4)',
    '  if ($cloaked -ne 0) { return $true }',
    '  $rootOwner = [DesktopPetVisibleWindows]::GetAncestor($hWnd, $GA_ROOTOWNER)',
    '  if ($rootOwner -eq [IntPtr]::Zero) { $rootOwner = $hWnd }',
    '  $walk = $rootOwner',
    '  while ($true) {',
    '    $popup = [DesktopPetVisibleWindows]::GetLastActivePopup($walk)',
    '    if ($popup -eq [IntPtr]::Zero -or $popup -eq $walk) { break }',
    '    if ([DesktopPetVisibleWindows]::IsWindowVisible($popup)) { break }',
    '    $walk = $popup',
    '  }',
    '  if ($walk -ne $hWnd -and ($exStyle -band $WS_EX_APPWINDOW) -eq 0) { return $true }',
    '  $rect = New-Object DesktopPetVisibleWindows+RECT',
    '  if (-not [DesktopPetVisibleWindows]::GetWindowRect($hWnd, [ref]$rect)) { return $true }',
    '  if (($rect.Right - $rect.Left) -lt 120 -or ($rect.Bottom - $rect.Top) -lt 80) { return $true }',
    '  $builder = New-Object System.Text.StringBuilder ($length + 1)',
    '  [void][DesktopPetVisibleWindows]::GetWindowText($hWnd, $builder, $builder.Capacity)',
    '  $title = $builder.ToString().Trim()',
    '  if ([string]::IsNullOrWhiteSpace($title)) { return $true }',
    '  $items.Add($title) | Out-Null',
    '  return $true',
    '}, [IntPtr]::Zero) | Out-Null',
    '$items | Select-Object -Unique | ConvertTo-Json -Compress',
  ].join('\n');
}

function getNativeWindowCaptureSourcesPowerShellScript(options = {}) {
  const includeThumbnails = options.includeThumbnails !== false;
  const thumbnailSize = options.thumbnailSize ?? { width: 320, height: 180 };
  const maxThumbnailWidth = Math.max(1, Math.round(Number(thumbnailSize.width) || 320));
  const maxThumbnailHeight = Math.max(1, Math.round(Number(thumbnailSize.height) || 180));

  return [
    '[Console]::InputEncoding = New-Object System.Text.UTF8Encoding -ArgumentList $false',
    '[Console]::OutputEncoding = New-Object System.Text.UTF8Encoding -ArgumentList $false',
    '$OutputEncoding = [Console]::OutputEncoding',
    'Add-Type -AssemblyName System.Drawing',
    'Add-Type @"',
    'using System;',
    'using System.Collections.Generic;',
    'using System.Runtime.InteropServices;',
    'using System.Text;',
    'public static class DesktopPetVisibleWindows {',
    '  public delegate bool EnumWindowsProc(IntPtr hWnd, IntPtr lParam);',
    '  [StructLayout(LayoutKind.Sequential)] public struct RECT { public int Left; public int Top; public int Right; public int Bottom; }',
    '  [DllImport("user32.dll")] public static extern bool EnumWindows(EnumWindowsProc lpEnumFunc, IntPtr lParam);',
    '  [DllImport("user32.dll")] public static extern bool IsWindowVisible(IntPtr hWnd);',
    '  [DllImport("user32.dll")] public static extern IntPtr GetShellWindow();',
    '  [DllImport("user32.dll", SetLastError=true)] public static extern int GetWindowText(IntPtr hWnd, StringBuilder text, int count);',
    '  [DllImport("user32.dll", SetLastError=true)] public static extern int GetWindowTextLength(IntPtr hWnd);',
    '  [DllImport("user32.dll")] public static extern bool GetWindowRect(IntPtr hWnd, out RECT rect);',
    '  [DllImport("user32.dll")] public static extern int GetWindowLong(IntPtr hWnd, int nIndex);',
    '  [DllImport("dwmapi.dll")] public static extern int DwmGetWindowAttribute(IntPtr hwnd, int dwAttribute, out int pvAttribute, int cbAttribute);',
    '  [DllImport("user32.dll")] public static extern IntPtr GetDC(IntPtr hWnd);',
    '  [DllImport("user32.dll")] public static extern int ReleaseDC(IntPtr hWnd, IntPtr hDC);',
    '  [DllImport("gdi32.dll")] public static extern IntPtr CreateCompatibleDC(IntPtr hdc);',
    '  [DllImport("gdi32.dll")] public static extern IntPtr CreateCompatibleBitmap(IntPtr hdc, int nWidth, int nHeight);',
    '  [DllImport("gdi32.dll")] public static extern IntPtr SelectObject(IntPtr hdc, IntPtr h);',
    '  [DllImport("gdi32.dll")] public static extern bool DeleteObject(IntPtr ho);',
    '  [DllImport("gdi32.dll")] public static extern bool DeleteDC(IntPtr hdc);',
    '  [DllImport("gdi32.dll")] public static extern bool StretchBlt(IntPtr hdcDest, int xDest, int yDest, int wDest, int hDest, IntPtr hdcSrc, int xSrc, int ySrc, int wSrc, int hSrc, int rop);',
    '  [DllImport("gdi32.dll")] public static extern int SetStretchBltMode(IntPtr hdc, int mode);',
    '}',
    '"@',
    'try { [System.Diagnostics.Process]::GetCurrentProcess().PriorityClass = [System.Diagnostics.ProcessPriorityClass]::Idle } catch {}',
    `$includeThumbnails = ${includeThumbnails ? '$true' : '$false'}`,
    '$WS_EX_TOOLWINDOW = 0x00000080',
    '$WS_EX_APPWINDOW = 0x00040000',
    '$WS_EX_NOACTIVATE = 0x08000000',
    '$GWL_EXSTYLE = -20',
    '$DWMWA_CLOAKED = 14',
    '$SRCCOPY = 0x00CC0020',
    '$HALFTONE = 4',
    '$items = New-Object System.Collections.Generic.List[object]',
    '$maxItems = 24',
    `$requestedWindowHandle = ${Number(String(options.sourceId || '').match(/^window:(\d+)/u)?.[1] || 0)}`,
    '$shellWindow = [DesktopPetVisibleWindows]::GetShellWindow()',
    'function New-WindowThumbnail($left, $top, $width, $height) {',
    '  if (-not $includeThumbnails) { return "" }',
    '  if ($width -le 0 -or $height -le 0) { return "" }',
    '  $thumbWidth = ' + maxThumbnailWidth,
    '  $thumbHeight = [Math]::Max(1, [int][Math]::Round($thumbWidth * $height / [Math]::Max(1, $width)))',
    '  if ($thumbHeight -gt ' + maxThumbnailHeight + ') {',
    '    $thumbHeight = ' + maxThumbnailHeight,
    '    $thumbWidth = [Math]::Max(1, [int][Math]::Round($thumbHeight * $width / [Math]::Max(1, $height)))',
    '  }',
    '  $screenDc = [DesktopPetVisibleWindows]::GetDC([IntPtr]::Zero)',
    '  if ($screenDc -eq [IntPtr]::Zero) { return "" }',
    '  $memoryDc = [DesktopPetVisibleWindows]::CreateCompatibleDC($screenDc)',
    '  if ($memoryDc -eq [IntPtr]::Zero) { [void][DesktopPetVisibleWindows]::ReleaseDC([IntPtr]::Zero, $screenDc); return "" }',
    '  $bitmapHandle = [DesktopPetVisibleWindows]::CreateCompatibleBitmap($screenDc, $thumbWidth, $thumbHeight)',
    '  if ($bitmapHandle -eq [IntPtr]::Zero) {',
    '    [void][DesktopPetVisibleWindows]::DeleteDC($memoryDc)',
    '    [void][DesktopPetVisibleWindows]::ReleaseDC([IntPtr]::Zero, $screenDc)',
    '    return ""',
    '  }',
    '  $oldObject = [DesktopPetVisibleWindows]::SelectObject($memoryDc, $bitmapHandle)',
    '  [void][DesktopPetVisibleWindows]::SetStretchBltMode($memoryDc, $HALFTONE)',
    '  $ok = [DesktopPetVisibleWindows]::StretchBlt($memoryDc, 0, 0, $thumbWidth, $thumbHeight, $screenDc, $left, $top, $width, $height, $SRCCOPY)',
    '  [void][DesktopPetVisibleWindows]::SelectObject($memoryDc, $oldObject)',
    '  [void][DesktopPetVisibleWindows]::DeleteDC($memoryDc)',
    '  [void][DesktopPetVisibleWindows]::ReleaseDC([IntPtr]::Zero, $screenDc)',
    '  if (-not $ok) { [void][DesktopPetVisibleWindows]::DeleteObject($bitmapHandle); return "" }',
    '  $image = [System.Drawing.Image]::FromHbitmap($bitmapHandle)',
    '  [void][DesktopPetVisibleWindows]::DeleteObject($bitmapHandle)',
    '  $stream = New-Object System.IO.MemoryStream',
    '  try {',
    '    $image.Save($stream, [System.Drawing.Imaging.ImageFormat]::Png)',
    '    return "data:image/png;base64," + [Convert]::ToBase64String($stream.ToArray())',
    '  } finally {',
    '    $stream.Dispose()',
    '    $image.Dispose()',
    '  }',
    '}',
    '[DesktopPetVisibleWindows]::EnumWindows({',
    '  param($hWnd, $lParam)',
    '  if ($items.Count -ge $maxItems) { return $true }',
    '  if ($hWnd -eq $shellWindow) { return $true }',
    '  if ($requestedWindowHandle -gt 0 -and $hWnd.ToInt64() -ne $requestedWindowHandle) { return $true }',
    '  if (-not [DesktopPetVisibleWindows]::IsWindowVisible($hWnd)) { return $true }',
    '  $length = [DesktopPetVisibleWindows]::GetWindowTextLength($hWnd)',
    '  if ($length -le 0) { return $true }',
    '  $exStyle = [DesktopPetVisibleWindows]::GetWindowLong($hWnd, $GWL_EXSTYLE)',
    '  if (($exStyle -band $WS_EX_TOOLWINDOW) -ne 0) { return $true }',
    '  if (($exStyle -band $WS_EX_NOACTIVATE) -ne 0 -and ($exStyle -band $WS_EX_APPWINDOW) -eq 0) { return $true }',
    '  $cloaked = 0',
    '  [void][DesktopPetVisibleWindows]::DwmGetWindowAttribute($hWnd, $DWMWA_CLOAKED, [ref]$cloaked, 4)',
    '  if ($cloaked -ne 0) { return $true }',
    '  $rect = New-Object DesktopPetVisibleWindows+RECT',
    '  if (-not [DesktopPetVisibleWindows]::GetWindowRect($hWnd, [ref]$rect)) { return $true }',
    '  $width = $rect.Right - $rect.Left',
    '  $height = $rect.Bottom - $rect.Top',
    '  if ($width -lt 120 -or $height -lt 80) { return $true }',
    '  $builder = New-Object System.Text.StringBuilder ($length + 1)',
    '  [void][DesktopPetVisibleWindows]::GetWindowText($hWnd, $builder, $builder.Capacity)',
    '  $title = $builder.ToString().Trim()',
    '  if ([string]::IsNullOrWhiteSpace($title)) { return $true }',
    '  $handle = $hWnd.ToInt64()',
    '  $items.Add([PSCustomObject]@{',
    '    id = "window:$($handle):0"',
    '    name = $title',
    '    type = "window"',
    '    displayId = $null',
    '    bounds = @{ x = [int]$rect.Left; y = [int]$rect.Top; width = [int]$width; height = [int]$height }',
    '    width = $width',
    '    height = $height',
    '    thumbnail = (New-WindowThumbnail $rect.Left $rect.Top $width $height)',
    '    appIcon = ""',
    '  }) | Out-Null',
    '  return $true',
    '}, [IntPtr]::Zero) | Out-Null',
    '$items | ConvertTo-Json -Depth 4 -Compress',
  ].join('\n');
}

function getNativeScreenPreviewPowerShellScript(displays = []) {
  const displayJson = JSON.stringify(displays.map((display) => ({
    id: String(display.id),
    x: Math.round(display.nativeX ?? display.x ?? 0),
    y: Math.round(display.nativeY ?? display.y ?? 0),
    width: Math.max(1, Math.round(display.nativeWidth ?? display.width ?? 1)),
    height: Math.max(1, Math.round(display.nativeHeight ?? display.height ?? 1)),
  })));

  return [
    '[Console]::InputEncoding = New-Object System.Text.UTF8Encoding -ArgumentList $false',
    '[Console]::OutputEncoding = New-Object System.Text.UTF8Encoding -ArgumentList $false',
    '$OutputEncoding = [Console]::OutputEncoding',
    'Add-Type -AssemblyName System.Drawing',
    `$displays = ConvertFrom-Json @'`,
    displayJson,
    `'@`,
    '$items = New-Object System.Collections.Generic.List[object]',
    'foreach ($display in @($displays)) {',
    '  $width = [Math]::Max(1, [int]$display.width)',
    '  $height = [Math]::Max(1, [int]$display.height)',
    '  $thumbWidth = ' + maxThumbnailWidth,
    '  $thumbHeight = [Math]::Max(1, [int][Math]::Round($thumbWidth * $height / [Math]::Max(1, $width)))',
    '  if ($thumbHeight -gt ' + maxThumbnailHeight + ') {',
    '    $thumbHeight = ' + maxThumbnailHeight,
    '    $thumbWidth = [Math]::Max(1, [int][Math]::Round($thumbHeight * $width / [Math]::Max(1, $height)))',
    '  }',
    '  $sourceBitmap = New-Object System.Drawing.Bitmap $width, $height',
    '  $sourceGraphics = [System.Drawing.Graphics]::FromImage($sourceBitmap)',
    '  $bitmap = New-Object System.Drawing.Bitmap $thumbWidth, $thumbHeight',
    '  $graphics = [System.Drawing.Graphics]::FromImage($bitmap)',
    '  try {',
    '    $sourceGraphics.CopyFromScreen([int]$display.x, [int]$display.y, 0, 0, (New-Object System.Drawing.Size $width, $height))',
    '    $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic',
    '    $graphics.DrawImage($sourceBitmap, 0, 0, $thumbWidth, $thumbHeight)',
    '    $stream = New-Object System.IO.MemoryStream',
    '    try {',
    '      $bitmap.Save($stream, [System.Drawing.Imaging.ImageFormat]::Png)',
    '      $thumbnail = "data:image/png;base64," + [Convert]::ToBase64String($stream.ToArray())',
    '    } finally {',
    '      $stream.Dispose()',
    '    }',
    '  } catch {',
    '    $thumbnail = ""',
    '  } finally {',
    '    $graphics.Dispose()',
    '    $bitmap.Dispose()',
    '    $sourceGraphics.Dispose()',
    '    $sourceBitmap.Dispose()',
    '  }',
    '  $items.Add([PSCustomObject]@{ displayId = [string]$display.id; thumbnail = $thumbnail }) | Out-Null',
    '}',
    '$items | ConvertTo-Json -Depth 4 -Compress',
  ].join('\n');
}

module.exports = {
  getNativeDisplayBoundsPowerShellScript,
  getNativeScreenPreviewPowerShellScript,
  getNativeWindowCaptureSourcesPowerShellScript,
  getVisibleWindowTitlesPowerShellScript,
};
