const SCRIPT_PREAMBLE = [
  '[Console]::InputEncoding = New-Object System.Text.UTF8Encoding -ArgumentList $false',
  '[Console]::OutputEncoding = New-Object System.Text.UTF8Encoding -ArgumentList $false',
  '$OutputEncoding = [Console]::OutputEncoding',
  '$ErrorActionPreference = "Stop"',
  '$errors = New-Object System.Collections.Generic.List[string]',
  'function Read-RegistryValue($path, $name) {',
  '  try {',
  '    $item = Get-ItemProperty -LiteralPath $path -Name $name -ErrorAction Stop',
  '    return [string]$item.$name',
  '  } catch {',
  '    return ""',
  '  }',
  '}',
];

const SYSTEM_INFO_SOURCES = [
  '$cpu = $null',
  '$computer = $null',
  '$os = $null',
  '$gpus = @()',
  'try { $cpu = Get-CimInstance Win32_Processor -ErrorAction Stop | Select-Object -First 1 } catch { $errors.Add("Win32_Processor: " + $_.Exception.Message) | Out-Null }',
  'try { $computer = Get-CimInstance Win32_ComputerSystem -ErrorAction Stop | Select-Object -First 1 } catch { $errors.Add("Win32_ComputerSystem: " + $_.Exception.Message) | Out-Null }',
  'try { $os = Get-CimInstance Win32_OperatingSystem -ErrorAction Stop | Select-Object -First 1 } catch { $errors.Add("Win32_OperatingSystem: " + $_.Exception.Message) | Out-Null }',
  'try { $gpus = @(Get-CimInstance Win32_VideoController -ErrorAction Stop) } catch { $errors.Add("Win32_VideoController: " + $_.Exception.Message) | Out-Null }',
  '$computerInfo = $null',
  'try {',
  '  Add-Type -AssemblyName Microsoft.VisualBasic -ErrorAction Stop',
  '  $computerInfo = New-Object Microsoft.VisualBasic.Devices.ComputerInfo',
  '} catch {',
  '  $errors.Add("ComputerInfo: " + $_.Exception.Message) | Out-Null',
  '}',
  '$cpuRegistryPath = "HKLM:\\HARDWARE\\DESCRIPTION\\System\\CentralProcessor\\0"',
  '$windowsRegistryPath = "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion"',
  '$registryCpuName = Read-RegistryValue $cpuRegistryPath "ProcessorNameString"',
  '$registryCpuVendor = Read-RegistryValue $cpuRegistryPath "VendorIdentifier"',
  '$registryCpuMHzRaw = Read-RegistryValue $cpuRegistryPath "~MHz"',
  '$registryProductName = Read-RegistryValue $windowsRegistryPath "ProductName"',
  '$registryEditionId = Read-RegistryValue $windowsRegistryPath "EditionID"',
  '$registryDisplayVersion = Read-RegistryValue $windowsRegistryPath "DisplayVersion"',
  '$registryBuildNumber = Read-RegistryValue $windowsRegistryPath "CurrentBuildNumber"',
];

const SYSTEM_INFO_FALLBACKS = [
  '$cpuModel = ""',
  'if ($cpu -and $cpu.Name) { $cpuModel = [string]$cpu.Name } elseif ($registryCpuName) { $cpuModel = [string]$registryCpuName }',
  '$cpuManufacturer = ""',
  'if ($cpu -and $cpu.Manufacturer) { $cpuManufacturer = [string]$cpu.Manufacturer } elseif ($registryCpuVendor) { $cpuManufacturer = [string]$registryCpuVendor }',
  '$cpuPhysicalCores = 0',
  'if ($cpu -and $cpu.NumberOfCores) { $cpuPhysicalCores = [int]$cpu.NumberOfCores }',
  '$cpuLogicalCores = 0',
  'if ($cpu -and $cpu.NumberOfLogicalProcessors) { $cpuLogicalCores = [int]$cpu.NumberOfLogicalProcessors }',
  '$cpuMaxClockMHz = 0',
  'if ($cpu -and $cpu.MaxClockSpeed) { $cpuMaxClockMHz = [int]$cpu.MaxClockSpeed } elseif ($registryCpuMHzRaw) { $cpuMaxClockMHz = [int]$registryCpuMHzRaw }',
  '$computerManufacturer = ""',
  'if ($computer -and $computer.Manufacturer) { $computerManufacturer = [string]$computer.Manufacturer }',
  '$computerModel = ""',
  'if ($computer -and $computer.Model) { $computerModel = [string]$computer.Model }',
  '$totalPhysicalMemoryBytes = 0',
  'if ($computer -and $computer.TotalPhysicalMemory) { $totalPhysicalMemoryBytes = [double]$computer.TotalPhysicalMemory } elseif ($computerInfo) { $totalPhysicalMemoryBytes = [double]$computerInfo.TotalPhysicalMemory }',
  '$totalVisibleBytes = 0',
  'if ($os -and $os.TotalVisibleMemorySize) { $totalVisibleBytes = [double]$os.TotalVisibleMemorySize * 1024 } elseif ($computerInfo) { $totalVisibleBytes = [double]$computerInfo.TotalPhysicalMemory }',
  '$freePhysicalBytes = 0',
  'if ($os -and $os.FreePhysicalMemory) { $freePhysicalBytes = [double]$os.FreePhysicalMemory * 1024 } elseif ($computerInfo) { $freePhysicalBytes = [double]$computerInfo.AvailablePhysicalMemory }',
  '$osCaption = ""',
  'if ($os -and $os.Caption) { $osCaption = [string]$os.Caption } elseif ($computerInfo -and $computerInfo.OSFullName) { $osCaption = [string]$computerInfo.OSFullName } elseif ($registryProductName) { $osCaption = [string]$registryProductName }',
  '$osVersion = ""',
  'if ($os -and $os.Version) { $osVersion = [string]$os.Version } elseif ($computerInfo -and $computerInfo.OSVersion) { $osVersion = [string]$computerInfo.OSVersion }',
  '$osBuildNumber = ""',
  'if ($os -and $os.BuildNumber) { $osBuildNumber = [string]$os.BuildNumber } elseif ($registryBuildNumber) { $osBuildNumber = [string]$registryBuildNumber }',
  '$osArchitecture = ""',
  'if ($os -and $os.OSArchitecture) { $osArchitecture = [string]$os.OSArchitecture }',
  '$osInstallDate = ""',
  'if ($os -and $os.InstallDate) { $osInstallDate = [string]$os.InstallDate }',
  '$osLastBootUpTime = ""',
  'if ($os -and $os.LastBootUpTime) { $osLastBootUpTime = [string]$os.LastBootUpTime }',
];

const SYSTEM_INFO_OUTPUT = [
  '$gpuItems = foreach ($gpu in $gpus) {',
  '  [PSCustomObject]@{',
  '    name = [string]$gpu.Name',
  '    adapterRamBytes = [double]$gpu.AdapterRAM',
  '    driverVersion = [string]$gpu.DriverVersion',
  '    videoProcessor = [string]$gpu.VideoProcessor',
  '    pnpDeviceId = [string]$gpu.PNPDeviceID',
  '  }',
  '}',
  '[PSCustomObject]@{',
  '  errors = @($errors)',
  '  cpu = [PSCustomObject]@{',
  '    model = $cpuModel',
  '    manufacturer = $cpuManufacturer',
  '    physicalCores = $cpuPhysicalCores',
  '    logicalCores = $cpuLogicalCores',
  '    maxClockMHz = $cpuMaxClockMHz',
  '  }',
  '  computer = [PSCustomObject]@{',
  '    manufacturer = $computerManufacturer',
  '    model = $computerModel',
  '    totalPhysicalMemoryBytes = $totalPhysicalMemoryBytes',
  '  }',
  '  memory = [PSCustomObject]@{',
  '    totalVisibleBytes = $totalVisibleBytes',
  '    freePhysicalBytes = $freePhysicalBytes',
  '  }',
  '  os = [PSCustomObject]@{',
  '    caption = $osCaption',
  '    displayVersion = [string]$registryDisplayVersion',
  '    editionId = [string]$registryEditionId',
  '    version = $osVersion',
  '    buildNumber = $osBuildNumber',
  '    architecture = $osArchitecture',
  '    installDate = $osInstallDate',
  '    lastBootUpTime = $osLastBootUpTime',
  '  }',
  '  gpu = $gpuItems',
  '} | ConvertTo-Json -Depth 6 -Compress',
];

function getWindowsSystemInfoPowerShellScript() {
  return [
    ...SCRIPT_PREAMBLE,
    ...SYSTEM_INFO_SOURCES,
    ...SYSTEM_INFO_FALLBACKS,
    ...SYSTEM_INFO_OUTPUT,
  ].join('\n');
}

module.exports = { getWindowsSystemInfoPowerShellScript };
