function createWindowManagerState() {
  return {
    mainWindow: null,
    postDragInputProxyWindow: null,
    postDragInputProxyReady: false,
    postDragInputProxyPointerActive: false,
    postDragInputProxyRegions: [],
    postDragInputProxyPendingRegions: null,
    postDragInputProxyShapeSignature: '',
    postDragInputProxyIdleDestroyTimer: null,
    settingsWindow: null,
    chatWindow: null,
    tray: null,
    isQuitting: false,
    isShellSettingsOpen: false,
    isPointerPassthrough: false,
    isPointerPassthroughForwarding: false,
    requestedPointerPassthrough: false,
    interactiveWindowShapeApplied: false,
    interactiveWindowShapeRegions: [],
    interactiveWindowShapeSignature: '',
    pendingInteractiveWindowShapeRegionsAfterPetDragHold: null,
    pendingInteractiveWindowShapeSignatureAfterPetDragHold: '',
    pendingInteractiveWindowShapeReceivedAtAfterPetDragHold: 0,
    petDragFullWindowShapeHoldTimer: null,
    petDragFullWindowShapeEndedAt: 0,
    petDragFullWindowShapeHoldUntil: 0,
    petDragNativeShapeActive: false,
    latestSharedState: null,
    wasInteractiveDialogueChatActive: false,
    mainTopmostGuard: null,
    mainInteractiveLayerWarmupCompleted: false,
    mainInteractiveLayerWarmupRestoreTimer: null,
    mainInteractiveLayerWarmupTimer: null,
    mainWindowCanShow: false,
    mainWindowRendererRecoveryInProgress: false,
    mainWindowRendererStartupRecoveryCount: 0,
    mainWindowRendererReadyFallbackTimer: null,
    mainWindowRendererReadyToShow: false,
    settingsWindowDisplayRefreshTimer: null,
    settingsWindowContentRefreshAt: 0,
    settingsWindowReadyPromise: null,
    topmostStateByWindow: new WeakMap(),
  };
}

module.exports = { createWindowManagerState };
