const CURRENT_WINDOW_COMPACT_MINIMUM_SIZE_KEY = '__desktopPetCompactMinimumSizeActive';

const COMPACT_WINDOW_BOUNDS = {
  width: 520,
  height: 720,
  minWidth: 420,
  minHeight: 560,
  maxWidth: 720,
  maxHeight: 960,
};

const SETTINGS_PANEL_WINDOW_BOUNDS = {
  width: 1440,
  height: 820,
  minWidth: 1180,
  minHeight: 600,
};

const CHAT_PANEL_WINDOW_BOUNDS = {
  width: 1280,
  height: 820,
  minWidth: 760,
  minHeight: 560,
  maxWidth: 8192,
  maxHeight: 1248,
};
const INTERACTIVE_CHAT_PANEL_WINDOW_BOUNDS = {
  width: 960,
  height: 300,
  minWidth: 620,
  minHeight: 240,
  maxWidth: 8192,
  maxHeight: 900,
};
const INTERACTIVE_CHAT_PANEL_CENTER_Y_RATIO = 0.69;

const TOPMOST_WINDOW_LEVEL = 'screen-saver';
const AREA_PICKER_TOPMOST_WINDOW_LEVEL = 'pop-up-menu';
const MAIN_TOPMOST_RELATIVE_LEVEL = 1;
const POST_DRAG_INPUT_PROXY_TOPMOST_RELATIVE_LEVEL = 2;
const POST_DRAG_INPUT_PROXY_IDLE_DESTROY_MS = 5_000;
const AUX_TOPMOST_RELATIVE_LEVEL = 3;
const PERSISTENT_AREA_BORDER_TOPMOST_RELATIVE_LEVEL = 4;
const AREA_PICKER_TOPMOST_RELATIVE_LEVEL = 5;
const SETTINGS_WINDOW_SHOW_DISPLAY_REFRESH_DELAY_MS = 80;
const SETTINGS_WINDOW_SHOW_CAPTURE_REFRESH_DELAY_MS = 1600;
const SETTINGS_WINDOW_CONTENT_REFRESH_COOLDOWN_MS = 5000;
const DISPLAY_ENVIRONMENT_BROADCAST_DELAY_MS = 120;
const TOPMOST_GUARD_INTERVAL_MS = 1200;

const PET_DRAG_FULL_WINDOW_SHAPE_HOLD_MS = 720;
const MAIN_INTERACTIVE_LAYER_WARMUP_DELAY_MS = 600;
const MAIN_INTERACTIVE_LAYER_WARMUP_RESTORE_DELAY_MS = 80;
const MAIN_WINDOW_RENDERER_READY_TIMEOUT_MS = 10_000;
const MAIN_WINDOW_RENDERER_HEALTH_TIMEOUT_MS = 1_500;
const MAIN_WINDOW_RENDERER_STARTUP_RECOVERY_LIMIT = 1;
const MAIN_INTERACTIVE_LAYER_WARMUP_REGION = {
  height: 1,
  width: 1,
  x: 0,
  y: 0,
};

module.exports = {
  CURRENT_WINDOW_COMPACT_MINIMUM_SIZE_KEY,
  COMPACT_WINDOW_BOUNDS,
  SETTINGS_PANEL_WINDOW_BOUNDS,
  CHAT_PANEL_WINDOW_BOUNDS,
  INTERACTIVE_CHAT_PANEL_WINDOW_BOUNDS,
  INTERACTIVE_CHAT_PANEL_CENTER_Y_RATIO,
  TOPMOST_WINDOW_LEVEL,
  AREA_PICKER_TOPMOST_WINDOW_LEVEL,
  MAIN_TOPMOST_RELATIVE_LEVEL,
  POST_DRAG_INPUT_PROXY_TOPMOST_RELATIVE_LEVEL,
  POST_DRAG_INPUT_PROXY_IDLE_DESTROY_MS,
  AUX_TOPMOST_RELATIVE_LEVEL,
  PERSISTENT_AREA_BORDER_TOPMOST_RELATIVE_LEVEL,
  AREA_PICKER_TOPMOST_RELATIVE_LEVEL,
  SETTINGS_WINDOW_SHOW_DISPLAY_REFRESH_DELAY_MS,
  SETTINGS_WINDOW_SHOW_CAPTURE_REFRESH_DELAY_MS,
  SETTINGS_WINDOW_CONTENT_REFRESH_COOLDOWN_MS,
  DISPLAY_ENVIRONMENT_BROADCAST_DELAY_MS,
  TOPMOST_GUARD_INTERVAL_MS,
  PET_DRAG_FULL_WINDOW_SHAPE_HOLD_MS,
  MAIN_INTERACTIVE_LAYER_WARMUP_DELAY_MS,
  MAIN_INTERACTIVE_LAYER_WARMUP_RESTORE_DELAY_MS,
  MAIN_WINDOW_RENDERER_READY_TIMEOUT_MS,
  MAIN_WINDOW_RENDERER_HEALTH_TIMEOUT_MS,
  MAIN_WINDOW_RENDERER_STARTUP_RECOVERY_LIMIT,
  MAIN_INTERACTIVE_LAYER_WARMUP_REGION,
};
