export const NEURAL_PERSONA_GRAPH_VIEW_WIDTH = 760;
export const NEURAL_PERSONA_GRAPH_VIEW_HEIGHT = 440;
export const NEURAL_PERSONA_GRAPH_INITIAL_WORKSPACE_SCALE = 3;
export const NEURAL_PERSONA_GRAPH_INITIAL_WORKSPACE_WIDTH = (
  NEURAL_PERSONA_GRAPH_VIEW_WIDTH * NEURAL_PERSONA_GRAPH_INITIAL_WORKSPACE_SCALE
);
export const NEURAL_PERSONA_GRAPH_INITIAL_WORKSPACE_HEIGHT = (
  NEURAL_PERSONA_GRAPH_VIEW_HEIGHT * NEURAL_PERSONA_GRAPH_INITIAL_WORKSPACE_SCALE
);

export const NEURAL_PERSONA_GRAPH_INITIAL_ORIGIN = {
  x: (NEURAL_PERSONA_GRAPH_INITIAL_WORKSPACE_WIDTH - NEURAL_PERSONA_GRAPH_VIEW_WIDTH) / 2,
  y: (NEURAL_PERSONA_GRAPH_INITIAL_WORKSPACE_HEIGHT - NEURAL_PERSONA_GRAPH_VIEW_HEIGHT) / 2,
};
