import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import {
  type AgentSessionV3PilotCorpusBatchIndex,
} from './agent-session-v3-pilot-corpus-batch-index-report.ts';
import { runAgentSessionV3PilotExternalSampleCorpusManifestTemplate } from './agent-session-v3-pilot-external-sample-corpus-manifest-template.ts';
import {
  type AgentSessionV3PilotExternalSampleCorpusManifest,
} from './agent-session-v3-pilot-external-sample-corpus-manifest-loader.ts';

export interface RunAgentSessionV3PilotRealCorpusBatchIntakeTemplateOptions {
  includeJsonText?: boolean;
  outDir?: string | null;
  prettyJson?: boolean;
}

export interface AgentSessionV3PilotRealCorpusBatchIntakeTemplateResult {
  index: AgentSessionV3PilotCorpusBatchIndex;
  indexPath: string | null;
  jsonText: string | null;
  kind: 'agent-session-v3-pilot-real-corpus-batch-intake-template';
  manifest: AgentSessionV3PilotExternalSampleCorpusManifest;
  manifestPath: string | null;
  notePath: string | null;
  noteText: string;
  readmePath: string | null;
  readmeText: string;
  summaryText: string;
  version: 1;
}

function parseAgentSessionV3PilotRealCorpusBatchIntakeTemplateArgs(
  args: readonly string[],
): RunAgentSessionV3PilotRealCorpusBatchIntakeTemplateOptions {
  let includeJsonText = false;
  let outDir: string | null = null;
  let prettyJson = false;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === '--json') {
      includeJsonText = true;
    } else if (arg === '--pretty') {
      includeJsonText = true;
      prettyJson = true;
    } else if (arg === '--out-dir') {
      const nextArg = args[index + 1];
      if (!nextArg) {
        throw new Error('Missing output directory after --out-dir.');
      }
      outDir = nextArg;
      index += 1;
    } else {
      throw new Error(`Unexpected argument: ${arg}`);
    }
  }

  return {
    includeJsonText,
    outDir,
    prettyJson,
  };
}

async function createAgentSessionV3PilotRealCorpusBatchManifestTemplate() {
  const template = await runAgentSessionV3PilotExternalSampleCorpusManifestTemplate();

  return {
    ...template.manifest,
    sources: [
      {
        label: 'replace-with-real-batch-label',
        path: './corpora/replace-with-debug-corpus.json',
      },
    ],
  };
}

function createAgentSessionV3PilotRealCorpusBatchIndexTemplate(): AgentSessionV3PilotCorpusBatchIndex {
  return {
    batches: [
      {
        generatedAt: 'replace-with-baseline-generated-at',
        label: 'baseline-artifact-flow',
        manifestPath: './baseline/explicit-debug-corpus-manifest.json',
        notes: 'optional baseline bundle generated by the baseline evidence artifact flow',
        sourceKind: 'baseline',
      },
      {
        generatedAt: 'replace-with-real-batch-generated-at',
        label: 'replace-with-real-batch-label',
        manifestPath: './real-corpus-manifest.json',
        notes: 'caller-owned manual or production-like exported corpus batch',
        sourceKind: 'production-like',
      },
    ],
    version: 1,
  };
}

function createAgentSessionV3PilotRealCorpusBatchReadmeText() {
  return [
    '# Agent Runtime v3 Pilot Real Corpus Batch Intake',
    '',
    'This directory is caller-owned. It organizes already exported debug corpus files for v3 pilot evidence review.',
    '',
    'Files:',
    '',
    '- `real-corpus-manifest.json`: replace the placeholder source with one or more exported debug corpus files.',
    '- `corpus-batch-index.json`: group the baseline manifest and real corpus manifest by source metadata.',
    '- `sample-note-template.md`: copy or fill this note for each real exported corpus batch before interpreting readiness.',
    '- `corpora/`: suggested location for copied or generated corpus JSON files. The template does not create or discover samples.',
    '',
    'Full manual checklist:',
    '',
    '- `PROJECT_AGENT_V3_REAL_CORPUS_BATCH_RUNBOOK.md`',
    '',
    'Preferred report-only validation from the project root:',
    '',
    '```powershell',
    'npx.cmd tsx .\\scripts\\agent-session-v3-pilot-real-corpus-batch-p0-intake-target-status-report.ts --dir .\\replace-with-intake-dir --pretty',
    'npx.cmd tsx .\\scripts\\agent-session-v3-pilot-real-corpus-batch-operator-checklist-report.ts --dir .\\replace-with-intake-dir --pretty',
    'npx.cmd tsx .\\scripts\\agent-session-v3-pilot-real-corpus-batch-evidence-summary.ts --dir .\\replace-with-intake-dir --pretty',
    'npx.cmd tsx .\\scripts\\agent-session-v3-pilot-real-corpus-batch-intake-validator.ts --dir .\\replace-with-intake-dir --pretty',
    'npx.cmd tsx .\\scripts\\agent-session-v3-pilot-real-corpus-batch-source-declaration-preflight.ts --dir .\\replace-with-intake-dir --expected-source real-exported --pretty',
    '```',
    '',
    'P0 target signal meaning:',
    '',
    '- `missing`: no supplied intake currently supports that P0 evidence target.',
    '- `blocked`: at least one supplied supporting intake has blocker evidence.',
    '- `review-needed`: supporting intake evidence exists, but still needs human interpretation.',
    '- `ready-for-manual-review`: supporting intake evidence has no machine-detected blocker or review item. This still does not mean production-ready.',
    '',
    'Operator checklist status meaning:',
    '',
    '- `blocked`: fix blocker checklist items before manual interpretation.',
    '- `review-needed`: machine-readable checks ran far enough, but review items still need human interpretation.',
    '- `ready-for-manual-review`: no blocker or review checklist items were found. This still does not mean production-ready.',
    '',
    'Validator status meaning:',
    '',
    '- `missing`: required manifest or index files are absent.',
    '- `empty`: the manifest or index exists but has no usable evidence entries.',
    '- `ready`: current checks passed for the loaded batches, but this is not production readiness.',
    '- `mixed`: at least one batch is ready and at least one batch needs review.',
    '- `not-ready`: at least one indexed report has failed readiness checks.',
    '',
    'Evidence summary status meaning:',
    '',
    '- `blocked`: required files, schema, paths, consistency, or indexed readiness must be fixed before manual interpretation.',
    '- `manual-review-needed`: machine-readable checks passed far enough to review, but mixed evidence or open notes need human interpretation.',
    '- `manual-review-ready`: no blocker or review gaps were found by the summary. This still does not mean production-ready.',
    '',
    'Optional direct report-only checks from the project root:',
    '',
    '```powershell',
    'npx.cmd tsx .\\scripts\\agent-session-v3-pilot-real-corpus-batch-schema-shape-report.ts --dir .\\replace-with-intake-dir --pretty',
    'npx.cmd tsx .\\scripts\\agent-session-v3-pilot-real-corpus-batch-path-health-report.ts --dir .\\replace-with-intake-dir --pretty',
    'npx.cmd tsx .\\scripts\\agent-session-v3-pilot-real-corpus-batch-consistency-report.ts --dir .\\replace-with-intake-dir --pretty',
    'npx.cmd tsx .\\scripts\\agent-session-v3-pilot-external-sample-corpus-manifest-loader.ts .\\replace-with-intake-dir\\real-corpus-manifest.json --report --pretty',
    'npx.cmd tsx .\\scripts\\agent-session-v3-pilot-corpus-batch-index-report.ts .\\replace-with-intake-dir\\corpus-batch-index.json --pretty',
    '```',
    '',
    'Guardrails:',
    '',
    '- Do not treat this template as production readiness.',
    '- Do not use it to collect samples, choose tools, route permissions, execute tools, decide recovery, or replace `AgentSessionV2`.',
    '- Keep all paths and thresholds caller-reviewed before using the reports for manual calibration.',
  ].join('\n');
}

function createAgentSessionV3PilotRealCorpusBatchSampleNoteText() {
  return [
    '# Agent Runtime v3 Pilot Real Corpus Batch Sample Note',
    '',
    'This note is caller-owned. Fill it for each already exported real or production-like debug corpus batch before interpreting readiness reports.',
    '',
    '## Batch Identity',
    '',
    '- Batch label: replace-with-real-batch-label',
    '- Export date: replace-with-export-date',
    '- Source environment: replace-with-machine-app-mode-or-branch',
    '- Scenario family: replace-with-scenario-family',
    '- Export command or source: replace-with-export-command-or-manual-source',
    '- Sample source: replace-with-sample-source-real-exported-rehearsal-or-unknown',
    '- Sample source status: replace-with-sample-source-status',
    '- Corpus file paths: replace-with-corpus-json-paths',
    '- Approximate sample count: replace-with-sample-count',
    '- Known unusual cases: none recorded',
    '',
    '## Validator Result',
    '',
    '- Validator command: `npx.cmd tsx .\\scripts\\agent-session-v3-pilot-real-corpus-batch-intake-validator.ts --dir .\\replace-with-intake-dir --pretty`',
    '- Validator status: replace-with-ready-mixed-not-ready-empty-or-missing',
    '- Manifest sources: replace-with-manifestSources',
    '- Index manifests: replace-with-indexManifests',
    '- Readiness counts: ready=replace mixed=replace notReady=replace empty=replace',
    '- Failed readiness checks: none recorded',
    '- Threshold profile comparison needed: yes/no and why',
    '',
    '## P0 Target Signals',
    '',
    '- P0 target status command: `npx.cmd tsx .\\scripts\\agent-session-v3-pilot-real-corpus-batch-p0-intake-target-status-report.ts --dir .\\replace-with-p0-intake-dir --pretty`',
    '- real-production-like-sample signal: replace-with-real-production-like-sample-signal',
    '- real-exported-corpus signal: replace-with-real-exported-corpus-signal',
    '- P0 signal interpretation: missing / blocked / review-needed / ready-for-manual-review',
    '',
    '## Manual Interpretation',
    '',
    '- Evidence quality: replace-with-short-assessment',
    '- What this batch proves: replace-with-scope',
    '- What this batch does not prove: replace-with-limitations',
    '- Follow-up samples needed: replace-with-next-samples',
    '- Threshold action: keep-current / compare-profiles / propose-manual-review',
    '',
    '## Guardrails',
    '',
    '- This note does not make v3 production-ready.',
    '- Do not use this note to choose tools, route permissions, execute tools, decide recovery, or replace `AgentSessionV2`.',
    '- Keep threshold changes manual and based on multiple reviewed batches.',
  ].join('\n');
}

function stringifyAgentSessionV3PilotRealCorpusBatchIntakeTemplateResult(
  result: AgentSessionV3PilotRealCorpusBatchIntakeTemplateResult,
  options: { prettyJson?: boolean } = {},
) {
  return JSON.stringify(result, null, options.prettyJson ? 2 : 0);
}

export async function runAgentSessionV3PilotRealCorpusBatchIntakeTemplate(
  options: RunAgentSessionV3PilotRealCorpusBatchIntakeTemplateOptions = {},
): Promise<AgentSessionV3PilotRealCorpusBatchIntakeTemplateResult> {
  const manifest = await createAgentSessionV3PilotRealCorpusBatchManifestTemplate();
  const index = createAgentSessionV3PilotRealCorpusBatchIndexTemplate();
  const noteText = createAgentSessionV3PilotRealCorpusBatchSampleNoteText();
  const readmeText = createAgentSessionV3PilotRealCorpusBatchReadmeText();
  const manifestPath = options.outDir
    ? path.join(options.outDir, 'real-corpus-manifest.json')
    : null;
  const indexPath = options.outDir
    ? path.join(options.outDir, 'corpus-batch-index.json')
    : null;
  const notePath = options.outDir
    ? path.join(options.outDir, 'sample-note-template.md')
    : null;
  const readmePath = options.outDir
    ? path.join(options.outDir, 'README.md')
    : null;

  const resultWithoutJson: AgentSessionV3PilotRealCorpusBatchIntakeTemplateResult = {
    index,
    indexPath,
    jsonText: null,
    kind: 'agent-session-v3-pilot-real-corpus-batch-intake-template',
    manifest,
    manifestPath,
    notePath,
    noteText,
    readmePath,
    readmeText,
    summaryText: [
      'AgentSessionV3PilotRealCorpusBatchIntakeTemplate',
      `sources=${manifest.sources?.length ?? 0}`,
      `batches=${index.batches?.length ?? 0}`,
      `outDir=${options.outDir ?? 'none'}`,
    ].join(' '),
    version: 1,
  };

  if (options.outDir && manifestPath && indexPath && notePath && readmePath) {
    await mkdir(options.outDir, {
      recursive: true,
    });
    await writeFile(
      manifestPath,
      JSON.stringify(manifest, null, options.prettyJson ? 2 : 0),
      'utf8',
    );
    await writeFile(
      indexPath,
      JSON.stringify(index, null, options.prettyJson ? 2 : 0),
      'utf8',
    );
    await writeFile(notePath, noteText, 'utf8');
    await writeFile(readmePath, readmeText, 'utf8');
  }

  return {
    ...resultWithoutJson,
    jsonText: options.includeJsonText
      ? stringifyAgentSessionV3PilotRealCorpusBatchIntakeTemplateResult(resultWithoutJson, {
        prettyJson: options.prettyJson,
      })
      : null,
  };
}

async function runAgentSessionV3PilotRealCorpusBatchIntakeTemplateCli() {
  const options = parseAgentSessionV3PilotRealCorpusBatchIntakeTemplateArgs(process.argv.slice(2));
  const result = await runAgentSessionV3PilotRealCorpusBatchIntakeTemplate(options);
  console.log(result.summaryText);
  if (result.manifestPath) {
    console.log(`manifestPath=${result.manifestPath}`);
  }
  if (result.indexPath) {
    console.log(`indexPath=${result.indexPath}`);
  }
  if (result.notePath) {
    console.log(`notePath=${result.notePath}`);
  }
  if (result.readmePath) {
    console.log(`readmePath=${result.readmePath}`);
  }
  if (result.jsonText) {
    console.log(result.jsonText);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  runAgentSessionV3PilotRealCorpusBatchIntakeTemplateCli().catch((error: unknown) => {
    const errorText = error instanceof Error ? error.message : String(error);
    console.error(errorText);
    process.exitCode = 1;
  });
}
