import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import {
  runAgentSessionV3PilotBaselineCorpusManifestReport,
  type AgentSessionV3PilotBaselineCorpusManifestReportResult,
} from './agent-session-v3-pilot-baseline-corpus-manifest-report.ts';
import {
  runAgentSessionV3PilotCorpusBatchIndexReport,
  type AgentSessionV3PilotCorpusBatchIndexReportResult,
} from './agent-session-v3-pilot-corpus-batch-index-report.ts';
import { runAgentSessionV3PilotCorpusBatchIndexTemplate } from './agent-session-v3-pilot-corpus-batch-index-template.ts';

export interface RunAgentSessionV3PilotBaselineEvidenceArtifactFlowOptions {
  includeJsonText?: boolean;
  maxShadowDebugSamples?: number;
  outDir: string;
  prettyJson?: boolean;
}

export interface AgentSessionV3PilotBaselineEvidenceArtifactFlowResult {
  baselineReport: AgentSessionV3PilotBaselineCorpusManifestReportResult;
  corpusPath: string;
  indexPath: string;
  indexReport: AgentSessionV3PilotCorpusBatchIndexReportResult;
  jsonText: string | null;
  kind: 'agent-session-v3-pilot-baseline-evidence-artifact-flow';
  manifestPath: string;
  reportText: string;
  summaryText: string;
  version: 1;
}

function parseAgentSessionV3PilotBaselineEvidenceArtifactFlowArgs(
  args: readonly string[],
): RunAgentSessionV3PilotBaselineEvidenceArtifactFlowOptions {
  let includeJsonText = false;
  let maxShadowDebugSamples: number | undefined;
  let outDir: string | null = null;
  let prettyJson = false;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === '--json') {
      includeJsonText = true;
    } else if (arg === '--pretty') {
      includeJsonText = true;
      prettyJson = true;
    } else if (arg === '--max-shadow') {
      const nextArg = args[index + 1];
      if (!nextArg) {
        throw new Error('Missing sample count after --max-shadow.');
      }
      maxShadowDebugSamples = Number(nextArg);
      index += 1;
    } else if (arg === '--out-dir') {
      const nextArg = args[index + 1];
      if (!nextArg) {
        throw new Error('Missing output directory after --out-dir.');
      }
      outDir = nextArg;
      index += 1;
    } else {
      throw new Error(`Unexpected argument: ${arg}`);
    }
  }

  if (!outDir) {
    throw new Error('Usage: npx tsx scripts/agent-session-v3-pilot-baseline-evidence-artifact-flow.ts --out-dir output-dir [--max-shadow count] [--json] [--pretty]');
  }

  return {
    includeJsonText,
    maxShadowDebugSamples,
    outDir,
    prettyJson,
  };
}

function createAgentSessionV3PilotBaselineEvidenceArtifactFlowSummaryText(options: {
  baselineReport: AgentSessionV3PilotBaselineCorpusManifestReportResult;
  indexReport: AgentSessionV3PilotCorpusBatchIndexReportResult;
}) {
  return [
    `AgentSessionV3PilotBaselineEvidenceArtifactFlow status=${options.indexReport.multiReport.statusCounts.ready > 0 ? 'ready' : 'not-ready'}`,
    `scenarios=${options.baselineReport.scenarioCount}`,
    `manifests=${options.indexReport.manifestCount}`,
    `sourceKinds=${options.indexReport.sourceKindSummaries.length}`,
  ].join(' ');
}

function createAgentSessionV3PilotBaselineEvidenceArtifactFlowJsonText(
  result: AgentSessionV3PilotBaselineEvidenceArtifactFlowResult,
  options: { prettyJson?: boolean } = {},
) {
  return JSON.stringify(result, null, options.prettyJson ? 2 : 0);
}

export async function runAgentSessionV3PilotBaselineEvidenceArtifactFlow(
  options: RunAgentSessionV3PilotBaselineEvidenceArtifactFlowOptions,
): Promise<AgentSessionV3PilotBaselineEvidenceArtifactFlowResult> {
  const baselineReport = await runAgentSessionV3PilotBaselineCorpusManifestReport({
    maxShadowDebugSamples: options.maxShadowDebugSamples,
    outDir: options.outDir,
    prettyJson: options.prettyJson,
  });
  const indexPath = path.join(options.outDir, 'corpus-batch-index.json');
  const indexTemplate = await runAgentSessionV3PilotCorpusBatchIndexTemplate({
    outPath: indexPath,
    prettyJson: options.prettyJson,
  });
  const index = {
    ...indexTemplate.index,
    batches: [
      {
        generatedAt: new Date(0).toISOString(),
        label: 'explicit-debug-baseline',
        manifestPath: path.basename(baselineReport.manifestPath),
        notes: 'baseline explicit-debug corpus generated by the v3 pilot artifact flow',
        sourceKind: 'baseline',
      },
    ],
  };

  await writeFile(
    indexPath,
    JSON.stringify(index, null, options.prettyJson ? 2 : 0),
    'utf8',
  );

  const indexReport = await runAgentSessionV3PilotCorpusBatchIndexReport({
    indexPath,
    prettyJson: options.prettyJson,
  });
  const summaryText = createAgentSessionV3PilotBaselineEvidenceArtifactFlowSummaryText({
    baselineReport,
    indexReport,
  });
  const resultWithoutJson: AgentSessionV3PilotBaselineEvidenceArtifactFlowResult = {
    baselineReport,
    corpusPath: baselineReport.corpusPath,
    indexPath,
    indexReport,
    jsonText: null,
    kind: 'agent-session-v3-pilot-baseline-evidence-artifact-flow',
    manifestPath: baselineReport.manifestPath,
    reportText: [summaryText, indexReport.reportText].join('\n'),
    summaryText,
    version: 1,
  };

  return {
    ...resultWithoutJson,
    jsonText: options.includeJsonText
      ? createAgentSessionV3PilotBaselineEvidenceArtifactFlowJsonText(resultWithoutJson, {
        prettyJson: options.prettyJson,
      })
      : null,
  };
}

async function runAgentSessionV3PilotBaselineEvidenceArtifactFlowCli() {
  const options = parseAgentSessionV3PilotBaselineEvidenceArtifactFlowArgs(process.argv.slice(2));
  const result = await runAgentSessionV3PilotBaselineEvidenceArtifactFlow(options);
  console.log(result.reportText);
  if (result.jsonText) {
    console.log(result.jsonText);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  runAgentSessionV3PilotBaselineEvidenceArtifactFlowCli().catch((error: unknown) => {
    const errorText = error instanceof Error ? error.message : String(error);
    console.error(errorText);
    process.exitCode = 1;
  });
}
