import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
  createAgentSessionV3PilotDebugSampleCorpusExport,
  createAgentSessionV3PilotShadowAgreementReport,
  createAgentSessionV3PilotShadowAgreementReportExport,
  createAgentSessionV3PilotShadowDebugExport,
  runAgentSessionV3PilotShadowMode,
  type AgentSessionV3PilotShadowAgreement,
} from '../src/agent/legacy/index.ts';
import { runAgentSessionV3PilotBaselineCorpusManifestReport } from './agent-session-v3-pilot-baseline-corpus-manifest-report.ts';
import { runAgentSessionV3PilotRealCorpusBatchIntakeTemplate } from './agent-session-v3-pilot-real-corpus-batch-intake-template.ts';
import { runAgentSessionV3PilotRealCorpusBatchReadinessRollupReport } from './agent-session-v3-pilot-real-corpus-batch-readiness-rollup-report.ts';
import { readProjectSources } from './smokeTestHarness.ts';

function createAgreement(
  options: Pick<AgentSessionV3PilotShadowAgreement, 'status' | 'v2Status'>,
): AgentSessionV3PilotShadowAgreement {
  return {
    expectations: [],
    observed: {
      lastEvent: null,
      phase: null,
      runnerStatus: null,
      shadowStatus: null,
      terminalStatus: null,
      transitionCount: null,
    },
    reason: `${options.status} real corpus readiness rollup sample`,
    status: options.status,
    v2Status: options.v2Status,
  };
}

function createCorpus(
  status: AgentSessionV3PilotShadowAgreement['status'],
  shadowExport: ReturnType<typeof createAgentSessionV3PilotShadowDebugExport>,
) {
  return createAgentSessionV3PilotDebugSampleCorpusExport({
    agreementReport: createAgentSessionV3PilotShadowAgreementReportExport(
      createAgentSessionV3PilotShadowAgreementReport([
        createAgreement({
          status,
          v2Status: status === 'aligned' ? 'completed' : 'failed',
        }),
      ]),
      {
        includeSamples: true,
      },
    ),
    shadowDebugSamples: [{
      label: `${status}-shadow`,
      shadow: shadowExport,
    }],
  });
}

const { rollupSource } = readProjectSources({
  rollupSource: 'scripts/agent-session-v3-pilot-real-corpus-batch-readiness-rollup-report.ts',
});

assert.match(
  rollupSource,
  /export async function runAgentSessionV3PilotRealCorpusBatchReadinessRollupReport/u,
  'real corpus batch readiness rollup report should expose a caller-owned runner.',
);
assert.doesNotMatch(
  rollupSource,
  /runAgentSessionV2|execute_desktop|observe_windows_and_apps|locate_screen_elements|buildAgentPermissionRoute|toolExecutor/u,
  'real corpus batch readiness rollup report should not know runtime execution, permissions, concrete tools, or tool execution.',
);
assert.doesNotMatch(
  rollupSource,
  /observe_windows_and_apps\s*->\s*locate_screen_elements\s*->\s*execute_desktop_sequence/iu,
  'real corpus batch readiness rollup report should not encode a fixed desktop tool chain.',
);

async function createReadyIntake(
  intakeDir: string,
  shadowExport: ReturnType<typeof createAgentSessionV3PilotShadowDebugExport>,
) {
  const intakeTemplate = await runAgentSessionV3PilotRealCorpusBatchIntakeTemplate({
    outDir: intakeDir,
    prettyJson: true,
  });
  await runAgentSessionV3PilotBaselineCorpusManifestReport({
    maxShadowDebugSamples: 3,
    outDir: path.join(intakeDir, 'baseline'),
    prettyJson: true,
  });

  const corpusDir = path.join(intakeDir, 'corpora');
  await mkdir(corpusDir, {
    recursive: true,
  });
  await writeFile(
    path.join(corpusDir, 'ready-corpus.json'),
    JSON.stringify(createCorpus('aligned', shadowExport)),
    'utf8',
  );

  assert.ok(intakeTemplate.indexPath);
  assert.ok(intakeTemplate.manifestPath);
  assert.ok(intakeTemplate.notePath);
  await writeFile(
    intakeTemplate.manifestPath,
    JSON.stringify({
      ...intakeTemplate.manifest,
      sources: [
        {
          label: 'ready-real-batch',
          path: './corpora/ready-corpus.json',
        },
      ],
    }, null, 2),
    'utf8',
  );
  await writeFile(
    intakeTemplate.indexPath,
    JSON.stringify({
      ...intakeTemplate.index,
      batches: [
        {
          generatedAt: '2026-06-23T10:00:00.000Z',
          label: 'baseline-artifact-flow',
          manifestPath: './baseline/explicit-debug-corpus-manifest.json',
          notes: 'baseline bundle generated by the reviewed baseline evidence artifact flow',
          sourceKind: 'baseline',
        },
        {
          generatedAt: '2026-06-23T10:05:00.000Z',
          label: 'ready-real-batch',
          manifestPath: './real-corpus-manifest.json',
          notes: 'caller-owned production-like exported corpus batch for manual review',
          sourceKind: 'production-like',
        },
      ],
    }, null, 2),
    'utf8',
  );
  await writeFile(
    intakeTemplate.notePath,
    (await readFile(intakeTemplate.notePath, 'utf8'))
      .replaceAll('replace-with-real-batch-label', 'ready-real-batch')
      .replaceAll('replace-with-export-date', '2026-06-23')
      .replaceAll('replace-with-machine-app-mode-or-branch', 'local-dev-agent-session-v2-shadow')
      .replaceAll('replace-with-scenario-family', 'terminal-state-alignment')
      .replaceAll('replace-with-export-command-or-manual-source', 'manual debug corpus export')
      .replaceAll('replace-with-sample-source-real-exported-rehearsal-or-unknown', 'real-exported')
      .replaceAll('replace-with-sample-source-status', 'real-exported-evidence')
      .replaceAll('replace-with-corpus-json-paths', './corpora/ready-corpus.json')
      .replaceAll('replace-with-sample-count', '12')
      .replaceAll('replace-with-intake-dir', 'tmp-agent-v3-real-corpus')
      .replaceAll('replace-with-ready-mixed-not-ready-empty-or-missing', 'ready')
      .replaceAll('replace-with-manifestSources', '1')
      .replaceAll('replace-with-indexManifests', '2')
      .replaceAll('ready=replace mixed=replace notReady=replace empty=replace', 'ready=2 mixed=0 notReady=0 empty=0')
      .replaceAll('yes/no and why', 'no, this batch only confirms local baseline alignment')
      .replaceAll('replace-with-p0-intake-dir', 'tmp-agent-v3-real-corpus')
      .replaceAll('replace-with-real-production-like-sample-signal', 'ready-for-manual-review')
      .replaceAll('replace-with-real-exported-corpus-signal', 'ready-for-manual-review')
      .replaceAll('replace-with-short-assessment', 'sufficient for manual baseline comparison')
      .replaceAll('replace-with-scope', 'v3 mirror alignment for this local sample set')
      .replaceAll('replace-with-limitations', 'no production runtime authority')
      .replaceAll('replace-with-next-samples', 'broader production-like traces')
      .replaceAll('keep-current / compare-profiles / propose-manual-review', 'keep-current'),
    'utf8',
  );
}

async function createMixedIntake(
  intakeDir: string,
  shadowExport: ReturnType<typeof createAgentSessionV3PilotShadowDebugExport>,
) {
  const intakeTemplate = await runAgentSessionV3PilotRealCorpusBatchIntakeTemplate({
    outDir: intakeDir,
    prettyJson: true,
  });
  await runAgentSessionV3PilotBaselineCorpusManifestReport({
    maxShadowDebugSamples: 3,
    outDir: path.join(intakeDir, 'baseline'),
    prettyJson: true,
  });

  const corpusDir = path.join(intakeDir, 'corpora');
  await mkdir(corpusDir, {
    recursive: true,
  });
  await writeFile(
    path.join(corpusDir, 'ready-corpus.json'),
    JSON.stringify(createCorpus('aligned', shadowExport)),
    'utf8',
  );
  await writeFile(
    path.join(corpusDir, 'mismatch-corpus.json'),
    JSON.stringify(createCorpus('mismatch', shadowExport)),
    'utf8',
  );

  assert.ok(intakeTemplate.manifestPath);
  await writeFile(
    intakeTemplate.manifestPath,
    JSON.stringify({
      ...intakeTemplate.manifest,
      sources: [
        {
          label: 'ready-real-batch',
          path: './corpora/ready-corpus.json',
        },
        {
          label: 'mismatch-real-batch',
          path: './corpora/mismatch-corpus.json',
        },
      ],
    }, null, 2),
    'utf8',
  );
}

function summaryIds(
  report: Awaited<ReturnType<typeof runAgentSessionV3PilotRealCorpusBatchReadinessRollupReport>>,
) {
  return new Set(report.checklistItemSummaries.map((item) => item.id));
}

const rootTempDir = await mkdtemp(path.join(tmpdir(), 'agent-v3-real-corpus-batch-readiness-rollup-'));
try {
  const shadowResult = await runAgentSessionV3PilotShadowMode({
    enabled: true,
    events: [
      {
        reason: 'begin real corpus readiness rollup sample',
        type: 'start',
      },
      {
        reason: 'terminal answer',
        route: 'terminal',
        terminalStatus: 'completed',
        type: 'model-decision-accepted',
      },
    ],
  });
  const shadowExport = createAgentSessionV3PilotShadowDebugExport(shadowResult);
  const missingIntakeDir = path.join(rootTempDir, 'missing-intake');
  const mixedIntakeDir = path.join(rootTempDir, 'mixed-intake');
  const readyIntakeDir = path.join(rootTempDir, 'ready-intake');

  await mkdir(missingIntakeDir, {
    recursive: true,
  });
  await createMixedIntake(mixedIntakeDir, shadowExport);
  await createReadyIntake(readyIntakeDir, shadowExport);

  const rollup = await runAgentSessionV3PilotRealCorpusBatchReadinessRollupReport({
    includeJsonText: true,
    intakeDirs: [
      missingIntakeDir,
      mixedIntakeDir,
      readyIntakeDir,
    ],
    prettyJson: true,
  });

  assert.equal(rollup.kind, 'agent-session-v3-pilot-real-corpus-batch-readiness-rollup-report');
  assert.equal(rollup.version, 1);
  assert.equal(rollup.status, 'blocked');
  assert.equal(rollup.intakeCount, 3);
  assert.deepEqual(rollup.statusCounts, {
    blocked: 1,
    readyForManualReview: 1,
    reviewNeeded: 1,
  });
  assert.ok(rollup.totalBlockerItems >= 4);
  assert.ok(rollup.totalReviewItems >= 4);
  assert.equal(rollup.totalInfoItems, 6);
  assert.equal(rollup.entries.length, 3);
  assert.ok(rollup.entries.some((entry) => entry.status === 'blocked' && entry.validatorStatus === 'missing'));
  assert.ok(rollup.entries.some((entry) => entry.status === 'review-needed' && entry.evidenceSummaryStatus === 'manual-review-needed'));
  assert.ok(rollup.entries.some((entry) => entry.status === 'ready-for-manual-review' && entry.evidenceSummaryStatus === 'manual-review-ready'));
  assert.ok(rollup.entries.some((entry) => entry.validatorStatus === 'missing' && entry.phaseCoverageCounts.status === 'unavailable'));
  assert.ok(rollup.entries.some((entry) => entry.status === 'review-needed' && entry.phaseCoverageCounts.status === 'clean'));
  assert.ok(rollup.entries.some((entry) => entry.status === 'ready-for-manual-review' && entry.phaseCoverageCounts.status === 'clean'));
  assert.ok(summaryIds(rollup).has('gap-missing-required-files'));
  assert.ok(summaryIds(rollup).has('gap-index-mixed'));
  assert.ok(summaryIds(rollup).has('gap-note-incomplete'));
  assert.ok(summaryIds(rollup).has('metadata-quality-issue-samples'));
  assert.ok(summaryIds(rollup).has('runbook-manual-review'));
  assert.match(rollup.summaryText, /status=blocked/u);
  assert.match(rollup.summaryText, /intakes=3/u);
  assert.match(rollup.reportText, /intakeEntries:/u);
  assert.match(rollup.reportText, /phaseCoverage=unavailable/u);
  assert.match(rollup.reportText, /phaseCoverage=clean/u);
  assert.match(rollup.reportText, /checklistItemSummaries:/u);
  assert.match(rollup.reportText, /id=gap-missing-required-files/u);
  assert.match(rollup.reportText, /id=gap-index-mixed/u);
  assert.ok(rollup.jsonText);
  assert.deepEqual(JSON.parse(rollup.jsonText), {
    ...rollup,
    jsonText: null,
  });

  const readyRollup = await runAgentSessionV3PilotRealCorpusBatchReadinessRollupReport({
    intakeDirs: [readyIntakeDir],
    prettyJson: true,
  });

  assert.equal(readyRollup.status, 'ready-for-manual-review');
  assert.deepEqual(readyRollup.statusCounts, {
    blocked: 0,
    readyForManualReview: 1,
    reviewNeeded: 0,
  });
  assert.equal(readyRollup.totalBlockerItems, 0);
  assert.equal(readyRollup.totalReviewItems, 0);
  assert.equal(readyRollup.totalInfoItems, 2);
  assert.equal(readyRollup.entries[0]?.phaseCoverageCounts.status, 'clean');
} finally {
  await rm(rootTempDir, {
    force: true,
    recursive: true,
  });
}

console.log('agent session v3 pilot real corpus batch readiness rollup report smoke ok');
