import { strict as assert } from 'node:assert';
import { readProjectFile } from './smokeTestHarness.ts';

const progressSource = readProjectFile('PROJECT_FEATURE_PROGRESS.md');
const guideSource = readProjectFile('PROJECT_NEW_FEATURE_INTEGRATION_GUIDE.md');

assert.match(progressSource, /Product Feature Progress/u);
assert.match(progressSource, /Life companion foundation/u);
assert.match(progressSource, /43%/u);
assert.match(progressSource, /Proactive interaction scheduler/u);
assert.match(progressSource, /65%/u);
assert.match(progressSource, /Proactive text prompt path/u);
assert.match(progressSource, /48%/u);
assert.match(progressSource, /Character growth/u);
assert.match(progressSource, /22%/u);
assert.match(progressSource, /settings\.lifeCompanion/u);
assert.match(progressSource, /src\/life-companion\/lifeCompanionSettings\.ts/u);
assert.match(progressSource, /src\/life-companion\/lifeCompanionGrowthController\.ts/u);
assert.match(progressSource, /src\/life-companion\/lifeCompanionGrowthStatus\.ts/u);
assert.match(progressSource, /src\/life-companion\/lifeCompanionScheduler\.ts/u);
assert.match(progressSource, /src\/life-companion\/lifeCompanionTextPromptPublisher\.ts/u);
assert.match(progressSource, /src\/life-companion\/lifeCompanionLlmPrompt\.ts/u);
assert.match(progressSource, /src\/life-companion\/lifeCompanionLlmPromptController\.ts/u);
assert.match(progressSource, /src\/life-companion\/lifeCompanionInteractionRunner\.ts/u);
assert.match(progressSource, /src\/life-companion\/lifeCompanionLlmBackoff\.ts/u);
assert.match(progressSource, /src\/life-companion\/lifeCompanionRuntimeOverride\.ts/u);
assert.match(progressSource, /src\/life-companion\/lifeCompanionRuntimeStatus\.ts/u);
assert.match(progressSource, /src\/hooks\/useLifeCompanionScheduler\.ts/u);
assert.match(progressSource, /SettingsLifeCompanionGrowthStatusRow/u);
assert.match(progressSource, /SettingsLifeCompanionRuntimeControls/u);
assert.match(progressSource, /SettingsLifeCompanionRuntimeStatusRow/u);
assert.match(progressSource, /SettingsLifeCompanionPanel/u);
assert.match(progressSource, /local template model message/u);
assert.match(progressSource, /LLM-generated model message/u);
assert.match(progressSource, /browser search mode blocked/u);
assert.match(progressSource, /failure backoff/u);
assert.match(progressSource, /desktop surface shows the character model and chat box/u);
assert.match(progressSource, /scripts\/life-companion-runtime-soak\.ts/u);
assert.match(progressSource, /scripts\/life-companion-runtime-override-smoke\.ts/u);
assert.match(progressSource, /scripts\/life-companion-growth-controller-smoke\.ts/u);
assert.match(progressSource, /29-point runtime soak/u);
assert.match(progressSource, /manual pause\/resume/u);
assert.match(progressSource, /passive\/food-consumed stat progression rules/u);
assert.match(progressSource, /Settings-only growth diagnostic row/u);
assert.match(progressSource, /runtime phase, local text state, LLM text state/u);
assert.match(progressSource, /does not call voice playback, trigger Skill performance, call MCP, or allow external web search/u);
assert.match(progressSource, /Next Recommended Slice/u);
assert.match(progressSource, /richer character growth progression events/u);
assert.match(progressSource, /Do not add desktop-facing debug\/status\/progress panels/u);
assert.match(progressSource, /Do not combine scheduler, growth progression, multi-character orchestration, and roleplay state machines/u);
assert.match(guideSource, /PROJECT_FEATURE_PROGRESS/u);
assert.match(guideSource, /character model and chat box only/u);
assert.match(guideSource, /Do not add desktop-facing panels for diagnostics, progress, or runtime state/u);

console.log('product feature progress smoke passed');
