export const NEURAL_PERSONA_GRAPH_TARGET_FPS = 60;
export const NEURAL_PERSONA_GRAPH_PHYSICS_FPS = 60;
export const NEURAL_PERSONA_GRAPH_PHYSICS_FRAME_MS = 1000 / NEURAL_PERSONA_GRAPH_PHYSICS_FPS;
export const NEURAL_PERSONA_GRAPH_BASE_PHYSICS_FRAME_MS = 1000 / 60;
